apiVersion: v1
kind: Secret
metadata:
  name: promoter-github-app-2025-10-04-15-49-55
  namespace: promoter-system
type: Opaque
data: {}
  # githubAppPrivateKey should be patched after applying using:
  # kubectl create secret generic promoter-github-app-2025-10-04-15-49-55 --from-file=githubAppPrivateKey=path/to/key.pem --dry-run=client -o yaml -n promoter-system | kubectl apply -f -

---
apiVersion: promoter.argoproj.io/v1alpha1
kind: ClusterScmProvider
metadata:
  name: promoter-test-2025-10-04-15-49-55
spec:
  secretRef:
    name: promoter-github-app-2025-10-04-15-49-55
  github:
    appID: 2063184
    installationID: 88716042

---
apiVersion: v1
kind: Namespace
metadata:
  name: promoter-test-0000
  labels:
    load-test: "true"
    load-test-run: "2025-10-04-15-49-55"
    asset-id: "0000"

---
apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: promoter-test-0000
  namespace: promoter-test-0000
spec:
  github:
    owner: crenshaw-dev
    name: promoter-test-0000-deployment
  scmProviderRef:
    name: promoter-test-2025-10-04-15-49-55
    kind: ClusterScmProvider
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: promoter-test-0000
  namespace: promoter-test-0000
spec:
  activeCommitStatuses:
  # The ArgoCDCommitStatus CR will maintain this commit status based on the application health.
  - key: argocd-health
  environments:
  - branch: environment/dev-use2
    autoMerge: true
  - branch: environment/dev-usw2
    autoMerge: true
  - branch: environment/stg-use2
    autoMerge: true
  - branch: environment/stg-usw2
    autoMerge: true
  - branch: environment/prd-use2
    autoMerge: false
  - branch: environment/prd-usw2
    autoMerge: false
  gitRepositoryRef:
    name: promoter-test-0000

---
apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: promoter-test-0000
  namespace: promoter-test-0000
spec:
  promotionStrategyRef:
    name: promoter-test-0000
  applicationSelector:
    matchLabels:
      asset: promoter-test-0000

---
