apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: promoter-loadtest
  namespace: argocd
spec:
  description: Load test project for deploying promoter manifests
  sourceRepos:
  - 'https://github.com/crenshaw-dev/gitops-promoter-loadtest'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  # Allow cluster-scoped resources
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: promoter.argoproj.io
    kind: ClusterScmProvider
  # Allow all GitOps Promoter resources (both deployed and child resources for resource tree visibility)
  namespaceResourceWhitelist:
  - group: ''
    kind: Secret
  - group: promoter.argoproj.io
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-loadtest
  namespace: argocd
spec:
  project: promoter-loadtest
  source:
    repoURL: 'https://github.com/crenshaw-dev/gitops-promoter-loadtest'
    targetRevision: HEAD
    path: runs/2025-10-04-15-37-44/manifests/promoter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
  # Ignore differences in Secret data to preserve manually patched private keys
  ignoreDifferences:
  - group: ''
    kind: Secret
    jsonPointers:
    - /data/githubAppPrivateKey

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: promoter-test-0000
  namespace: argocd
spec:
  description: Load test project for asset 0000
  sourceRepos:
  - 'https://github.com/crenshaw-dev/promoter-test-0000'
  - 'https://github.com/crenshaw-dev/promoter-test-0000-deployment'
  destinations:
  - namespace: 'promoter-test-0000-*'
    server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: v1
kind: Secret
metadata:
  name: promoter-test-0000-repo-write-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository-write
type: Opaque
stringData:
  type: git
  url: https://github.com/crenshaw-dev/promoter-test-0000-deployment
  githubAppID: "2063184"
  githubAppInstallationID: "88716042"
  githubAppPrivateKey: |
    # PRIVATE_KEY_PLACEHOLDER - Use kubectl patch to add your private key

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-test-0000-dev-use2
  namespace: argocd
  labels:
    asset: promoter-test-0000
spec:
  project: promoter-test-0000
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-test-0000-dev-use2
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/promoter-test-0000-deployment
      path: .
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environment/dev-use2-next
    syncSource:
      targetBranch: environment/dev-use2
      path: dev-use2
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-test-0000-dev-usw2
  namespace: argocd
  labels:
    asset: promoter-test-0000
spec:
  project: promoter-test-0000
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-test-0000-dev-usw2
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/promoter-test-0000-deployment
      path: .
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environment/dev-usw2-next
    syncSource:
      targetBranch: environment/dev-usw2
      path: dev-usw2
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-test-0000-stg-use2
  namespace: argocd
  labels:
    asset: promoter-test-0000
spec:
  project: promoter-test-0000
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-test-0000-stg-use2
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/promoter-test-0000-deployment
      path: .
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environment/stg-use2-next
    syncSource:
      targetBranch: environment/stg-use2
      path: stg-use2
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-test-0000-stg-usw2
  namespace: argocd
  labels:
    asset: promoter-test-0000
spec:
  project: promoter-test-0000
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-test-0000-stg-usw2
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/promoter-test-0000-deployment
      path: .
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environment/stg-usw2-next
    syncSource:
      targetBranch: environment/stg-usw2
      path: stg-usw2
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-test-0000-prd-use2
  namespace: argocd
  labels:
    asset: promoter-test-0000
spec:
  project: promoter-test-0000
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-test-0000-prd-use2
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/promoter-test-0000-deployment
      path: .
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environment/prd-use2-next
    syncSource:
      targetBranch: environment/prd-use2
      path: prd-use2
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-test-0000-prd-usw2
  namespace: argocd
  labels:
    asset: promoter-test-0000
spec:
  project: promoter-test-0000
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-test-0000-prd-usw2
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/promoter-test-0000-deployment
      path: .
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environment/prd-usw2-next
    syncSource:
      targetBranch: environment/prd-usw2
      path: prd-usw2
  syncPolicy:
    automated:
      selfHeal: true

---
