apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promoter-controller
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promoter
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - promoter-system
  endpoints:
    - port: https
      scheme: https
      path: /metrics
      interval: 30s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true

