apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Argo CD with namespace overlay (creates argocd namespace and installs Argo CD in it)
  - argocd-overlay
  # GitOps Promoter (installs in promoter-system namespace)
  - https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.13.0/install.yaml
  # Monitoring (Prometheus and Grafana with dashboards)
  - monitoring
  # RBAC for Prometheus to scrape GitOps Promoter metrics
  - rbac

# Apply patches for local testing configuration
patches:
  # Patch Argo CD server deployment to add GitOps Promoter UI extension
  - path: argocd/argocd-server-patch.yaml
  # Patch Argo CD ConfigMap to add deep links and reduce reconciliation timeout
  - path: argocd/argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  # Patch Promoter controller configuration for faster reconciliation
  - path: promoter/controller-config-patch.yaml
    target:
      kind: ControllerConfiguration
      name: promoter-controller-configuration
      namespace: promoter-system

